---
#------------------------------------
# Setup options
#------------------------------------
# path to where samples file is stored
samples_df: "/home/carsonjm/CarsonJM/phide_piper/config/samples_local.tsv"
# path to folder where outputs should be stored
results: "/home/carsonjm/results/phide_piper_test/"
# path to directory where large downloads should be stored
resources: "/home/carsonjm/resources/"

#------------------------------------
# Database options
#------------------------------------
# used to search for external viruses in samples
virus_db: "/gscratch/scrubbed/carsonjm/resources/hq_virus_db/combined_hq_genomes.fa"
# used to search for common k-mers in viral sequences
bacteria_db: "/gscratch/scrubbed/carsonjm/resources/uhog/bacteria/"
bacteria_db_meta: "/gscratch/scrubbed/carsonjm/resources/uhog/uhog_genome-all_metadata.tsv"

#------------------------------------
# Pipeline options
#------------------------------------
# reads, contigs, viruses, or processed viruses
input_data: "reads"
# 1. "reads": raw, unprocessed, paired-end reads
# 2. "contigs": preprocessed reads assembled into contigs
# 3. "vls":  preprocessed reads, assembled into contigs, and identified as viral (virus-like sequences)
# 4. "viruses":  preprocessed reads, assembled into contigs, identified as viral, quality-filtered, and dereplicated

#------------------------------------
# Rule customization
#------------------------------------
### Preprocessing ###
read_preprocessing:
  fastp_arguments: "--disable_adapter_trimming --dedup --correction --overrepresentation_analysis"
  fastp_threads: 8
  kneaddata_arguments: ""
  kneaddata_threads: 8

include_enrichment_module: True
virus_enrichment:
  viromeqc_arguments: ""
  viromeqc_threads: 8

read_assembly:
  assembly_modes: ["meta", "metaviral"]
  spades_arguments: ""
  spades_threads: 8
  quast_arguments: "--max-ref-num 0"
  min_contig_length: 1000

virus_identification:
  run_mgv: True
  mgv_threads: 8
  run_virsorter: True
  virsorter_cat: [1, 2, 3, 4, 5, 6]
  virsorter_arguments: "--db 2 --diamond"
  virsorter_threads: 8
  run_virfinder: True
  virfinder_min_score: 0.9
  virfinder_threads: 1
  run_virsorter2: True
  virsorter2_min_score: 0.5
  virsorter2_arguments: "--include-groups dsDNAphage"
  virsorter2_threads: 8
  run_vibrant: True
  vibrant_arguments: "-no_plot"
  vibrant_threads: 8
  run_deepvirfinder: True
  deepvirfinder_min_score: 0.9
  deepvirfinder_threads: 8
  run_genomad: True
  genomad_min_score: 0.8
  genomad_max_fdr: 0.05
  genomad_arguments: ""
  genomad_threads: 8
  run_external: True
  min_mash_score: 0.95
  min_mash_hashes: 850
  min_mash_multiplicity: 3
  mash_threads: 8

virus_dereplication:
  blast_arguments: ""
  min_ani: 99
  min_qcov: 100
  min_tcov: 0
  blast_threads: 8

virus_quality:
  checkv_arguments: ""
  min_completeness: 90
  max_bacterial_genes: 2
  min_viral_genes: 0
  remove_proviruses: True
  checkv_threads: 8

include_binning_module: False
virus_binning:
  max_completeness_to_bin: 90
  vrhyme_arguments: ""
  min_bin_completeness: 90
  vrhyme_threads: 8

virus_diversity:
  blast_arguments: ""
  min_ani: 95
  min_qcov: 85
  min_tcov: 0
  blast_threads: 8
  vcontact2_arguments: ""
  vcontact2_threads: 20

include_phylogeny_module: True
virus_phylogeny:
  hmmsearch_threads: 8
  max_evalue: 1
  max_percent_gaps: 95
  min_hits_per_genome: 3

include_host_module: True
virus_host:
  iphop_min_score: 90
  iphop_arguments: ""
  iphop_threads: 8
  min_phist_common_kmers: 2
  min_phist_agreement: 50
  phist_threads: 8

include_taxonomy_module: True
virus_taxonomy:
  genomad_min_genes: 1
  genomad_min_agreement: 0.5
  mmseqs_arguments: ""
  mmseqs_min_agreement: 0.5
  mmseqs_threads: 16

include_lifestyle_module: True
virus_lifestyle:
  bacphlip_arguments: ""
  bacphlip_confidence: 0.5
  bacphlip_threads: 8

include_function_module: True
virus_function:
  run_dramv: True
  dramv_arguments: ""
  dramv_threads: 10
