---
#------------------------------------
# Setup options
#------------------------------------
# path to where samples.tsv is stored
samples_df: "/gscratch/stf/carsonjm/CarsonJM/phide_piper/config/samples.tsv"
# path to folder where outputs should be stored
results: "/gscratch/scrubbed/carsonjm/results/phide_piper_test/"
# path to directory where downloaded databases should be stored
resources: "/gscratch/scrubbed/carsonjm/resources/"

#------------------------------------
# Database options
#------------------------------------
# used to search for external viruses in samples
virus_db: "/gscratch/scrubbed/carsonjm/resources/hq_virus_db/combined_hq_genomes.fa"
# used for PHIST search
bacteria_db: "/gscratch/scrubbed/carsonjm/resources/uhog/bacteria/"
bacteria_db_meta: "/gscratch/scrubbed/carsonjm/resources/uhog/uhog_genome-all_metadata.tsv"

#------------------------------------
# Pipeline options
#------------------------------------
# reads, contigs, viruses, or processed viruses
input_data: "reads"
# 1. "reads": raw, unprocessed, paired-end reads
# Modules 1 - 7 will run + annotation modules as specified
# 2. "contigs": preprocessed reads assembled into contigs
# Modules 4 - 7 will run + annotation modules as specified
# 3. "vls":  preprocessed reads, assembled into contigs, and identified as viral (virus-like sequences)
# Modules 5 - 7 will run + annotation modules as specified
# 4. "viruses":  preprocessed reads, assembled into contigs, identified as viral, quality-filtered, and dereplicated
# Only annotation modules will run as specified

#------------------------------------
# Rule customization
#------------------------------------
# General concepts:
# 1. For arguments options, simply insert additionaly arguments exactly as they would be entered on the command line
# Ex. fastp_arguments: "--disable_adapter_trimming --dedup --correction --overrepresentation_analysis"
# *Quotation marks are necessary
#
# 2. For threads, simply insert the number of threads you would like to use for a specific tool
# Ex. fastp_threads: 8
#
# 3. Some modules do not have to be run, these can be identified by looking for the include_*_module: lines
#    To run these module, make sure the True is inserted next these statements.
# Ex. include_enrichment_module: True
#

# Module 1: Read Preprocessing
read_preprocessing:
  fastp_arguments: "--disable_adapter_trimming --dedup --correction --overrepresentation_analysis"
  fastp_threads: 8
  kneaddata_arguments: ""
  kneaddata_threads: 8

# Module 2: Viral Enrichment
include_enrichment_module: True
virus_enrichment:
  viromeqc_arguments: ""
  viromeqc_threads: 8

# Module 3: Read Assembly
read_assembly:
  # Possible options are "meta", "metaviral" and "rnaviral"
  assembly_modes: ["meta", "metaviral"]
  spades_arguments: ""
  spades_threads: 8
  quast_arguments: "--max-ref-num 0"
  min_contig_length: 1000

# Module 4: Virus Identification
virus_identification:
  run_mgv: True
  mgv_threads: 8
  run_virsorter: True
  # Possible virsorter categories are 1,2,3,4,5 and 6
  virsorter_cat: [1, 2, 3, 4, 5, 6]
  virsorter_arguments: "--db 2 --diamond"
  virsorter_threads: 8
  run_virfinder: True
  virfinder_min_score: 0.9
  virfinder_threads: 1
  run_virsorter2: True
  virsorter2_min_score: 0.5
  virsorter2_arguments: "--include-groups dsDNAphage"
  virsorter2_threads: 8
  run_vibrant: True
  vibrant_arguments: "-no_plot"
  vibrant_threads: 8
  run_deepvirfinder: True
  deepvirfinder_min_score: 0.9
  deepvirfinder_threads: 8
  run_genomad: True
  genomad_min_score: 0.8
  genomad_max_fdr: 0.05
  genomad_arguments: ""
  genomad_threads: 8
  run_external: True
  # Roughly equates to identity (0.95 score ~= 95% identity)
  min_mash_score: 0.95
  # Roughly equates to breadth (850 hashes out of 1000 ~= 85% breadth)
  min_mash_hashes: 850
  # Roughly equates to coverage (3 multiplicity ~= 3x coverage)
  min_mash_multiplicity: 3
  mash_threads: 8

# Module 5: Virus Quality
virus_quality:
  checkv_arguments: ""
  min_completeness: 90
  max_bacterial_genes: 2
  min_viral_genes: 0
  # Remove any viruses flagged as provirus by CheckV
  remove_proviruses: True
  checkv_threads: 8

# Module 6: Virus Dereplication
virus_dereplication:
  blast_arguments: ""
  # average nucleotide identity
  min_ani: 99
  # query coverage
  min_qcov: 100
  # target coverage
  # typically left at 0, so AF is relative only to shorter sequence
  min_tcov: 0
  blast_threads: 8

# Module 7: Virus Diversity
virus_diversity:
  blast_arguments: ""
  # average nucleotide identity
  min_ani: 95
  # query coverage
  min_qcov: 85
  # target coverage
  # typically left at 0, so AF is relative only to shorter sequence
  min_tcov: 0
  blast_threads: 8
  vcontact2_arguments: "--db 'None'"
  vcontact2_threads: 20

# Module 7 extra: Virus Phylogeny
include_phylogeny_module: True
virus_phylogeny:
  hmmsearch_threads: 8
  max_evalue: 1
  # Max percent gaps in MSA
  max_percent_gaps: 95
  # Min number of CCP77 hits per genome to include in phylogeny
  min_hits_per_genome: 3

# Module 8: Virus Host
include_host_module: True
virus_host:
  # Roughly equates to precision
  iphop_min_score: 90
  iphop_arguments: ""
  iphop_threads: 8
  # Min common kmers between virus and bacterial genome to consider towards total
  min_phist_common_kmers: 2
  # Min agreement amongst PHIST kmers (all kmers from genomes with > min_phist_common_kmers)
  min_phist_agreement: 50
  phist_threads: 8

# Module 9: Virus Taxonomy
include_taxonomy_module: True
virus_taxonomy:
  # Min annotated genomad genes per genome to assign taxonomy
  genomad_min_genes: 1
  # Min taxonomic agreement amongst all genomad hits
  genomad_min_agreement: 0.5
  mmseqs_arguments: ""
  # Min agreement amongst all MMSeqs2 NCBI NR hits
  mmseqs_min_agreement: 0.5
  mmseqs_threads: 16

# Module 10: Virus Lifestyle
include_lifestyle_module: True
virus_lifestyle:
  bacphlip_arguments: ""
  # Min BACPHLIP confidence to assign lifestyle
  bacphlip_confidence: 0.5
  bacphlip_threads: 8

# Module 11: Virus Function
include_function_module: True
virus_function:
  dramv_arguments: ""
  dramv_threads: 10

# Module 12: Virus Analysis
virus_analysis:
  bowtie2_threads: 8
  metapop_arguments: ""
  metapop_threads: 8
  min_id: 95
  min_breadth: 85
  min_depth: 1
